######## WARNING WARNING ########
#
# Before running, make sure to run ./build-all.sh to tag the Spring Boot images!
#
######## WARNING WARNING ########
---
version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.9.5-management
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis:6.2.5
    ports:
      - "6379:6379"
  db:
    image: postgres:13.4
    environment:
      POSTGRES_PASSWORD: password
    ports:
    - "5432:5432"
    volumes:
      - type: bind
        source: ./docker/docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d
  api:
    image: vino-api:1.0.0
    environment:
      SPRING_PROFILES_ACTIVE: compose
    ports:
    - "8080:8080"
    depends_on:
      - rabbitmq
  listener:
    image: vino-listener:1.0.0
    environment:
      SPRING_PROFILES_ACTIVE: compose
      FILTER_TYPE: person
    ports:
      - "9090:9090"
    depends_on:
      - rabbitmq
      - db
