-- auto-generated definition
create table events
(
    id            integer generated by default as identity
        constraint events_pkey
            primary key,
    created_at    timestamp not null,
    event_payload jsonb,
    event_type    varchar(255),
    modified_at   timestamp not null
);

alter table events
    owner to postgres;

